// ==================== APP INITIALIZATION ====================

document.addEventListener('DOMContentLoaded', function() {
    initializeApp();
});

function initializeApp() {
    // Start with login page
    showLogin();
    
    // Log app info
    console.log('FixFirst Application Initialized');
    console.log('=================================');
    console.log('Demo Credentials:');
    console.log('Citizen: citizen@demo.com / demo');
    console.log('Authority: admin@demo.com / admin');
    console.log('=================================');
    console.log('Features:');
    console.log('- Smart Duplicate Detection (50m radius)');
    console.log('- Community Upvoting System');
    console.log('- Photo Evidence Upload');
    console.log('- GPS Location Tracking');
    console.log('- Real-time Priority Sorting');
    console.log('=================================');
}

// ==================== KEYBOARD SHORTCUTS ====================

document.addEventListener('keydown', function(e) {
    // ESC to close modals
    if (e.key === 'Escape') {
        closeModal();
        closeMapModal();
    }
});

// ==================== WINDOW UNLOAD WARNING ====================

window.addEventListener('beforeunload', function(e) {
    // Warn user if they have unsaved work
    if (AppState.isAuthenticated() && document.getElementById('reportForm')) {
        e.preventDefault();
        e.returnValue = '';
    }
});

// ==================== ERROR HANDLING ====================

window.addEventListener('error', function(e) {
    console.error('Application Error:', e.error);
});

// ==================== UTILITY FUNCTIONS ====================

// Print issue report (optional feature)
function printIssueReport(issueId) {
    const issue = AppState.getIssueById(issueId);
    if (!issue) return;
    
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
            <title>FixFirst - Issue Report #${issue.id}</title>
            <style>
                body { 
                    font-family: Arial, sans-serif; 
                    padding: 20px;
                    max-width: 800px;
                    margin: 0 auto;
                }
                h1 { color: #2563eb; }
                .info { margin: 10px 0; }
                .label { font-weight: bold; }
                img { max-width: 100%; margin: 20px 0; }
                .header {
                    border-bottom: 3px solid #2563eb;
                    padding-bottom: 10px;
                    margin-bottom: 20px;
                }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>FixFirst - Issue Report</h1>
                <p>Infrastructure Issue Reporting System</p>
            </div>
            <div class="info"><span class="label">Issue ID:</span> #${issue.id}</div>
            <div class="info"><span class="label">Type:</span> ${issue.type}</div>
            <div class="info"><span class="label">Description:</span> ${issue.desc}</div>
            <div class="info"><span class="label">Location:</span> ${issue.location}</div>
            <div class="info"><span class="label">GPS Coordinates:</span> ${issue.lat.toFixed(6)}, ${issue.lon.toFixed(6)}</div>
            <div class="info"><span class="label">Severity:</span> ${issue.severity.toUpperCase()}</div>
            <div class="info"><span class="label">Status:</span> ${issue.status.replace('-', ' ').toUpperCase()}</div>
            <div class="info"><span class="label">Upvotes:</span> ${issue.upvotes}</div>
            <div class="info"><span class="label">Reported:</span> ${formatDate(issue.createdAt)}</div>
            ${issue.openedAt ? `<div class="info"><span class="label">Work Started:</span> ${formatDate(issue.openedAt)}</div>` : ''}
            ${issue.resolvedAt ? `<div class="info"><span class="label">Resolved:</span> ${formatDate(issue.resolvedAt)}</div>` : ''}
            ${issue.image ? `<div class="info"><span class="label">Photo Evidence:</span><br><img src="${issue.image}" alt="Issue Photo"></div>` : ''}
            <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; text-align: center; color: #666;">
                <small>Generated by FixFirst - Report road issues. Fix them first.</small>
            </div>
        </body>
        </html>
    `);
    printWindow.document.close();
    printWindow.print();
}

// Export data as CSV (optional enhancement)
function exportIssuesCSV() {
    const issues = AppState.getIssues();
    
    let csv = 'ID,Type,Description,Location,Latitude,Longitude,Severity,Status,Upvotes,Reported,Opened,Resolved\n';
    
    issues.forEach(issue => {
        csv += `${issue.id},"${issue.type}","${issue.desc}","${issue.location}",${issue.lat},${issue.lon},${issue.severity},${issue.status},${issue.upvotes},${issue.createdAt.toISOString()},${issue.openedAt ? issue.openedAt.toISOString() : ''},${issue.resolvedAt ? issue.resolvedAt.toISOString() : ''}\n`;
    });
    
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fixfirst-issues-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
}

// Calculate statistics
function calculateStats() {
    const issues = AppState.getIssues();
    
    return {
        total: issues.length,
        onDeck: issues.filter(i => i.status === 'on-deck').length,
        inProgress: issues.filter(i => i.status === 'in-progress').length,
        resolved: issues.filter(i => i.status === 'resolved').length,
        high: issues.filter(i => i.severity === 'high').length,
        medium: issues.filter(i => i.severity === 'medium').length,
        low: issues.filter(i => i.severity === 'low').length,
        totalUpvotes: issues.reduce((sum, issue) => sum + issue.upvotes, 0),
        avgUpvotes: issues.length > 0 ? Math.round(issues.reduce((sum, issue) => sum + issue.upvotes, 0) / issues.length) : 0,
        avgResolutionTime: calculateAvgResolutionTime(issues),
        withPhotos: issues.filter(i => i.image).length
    };
}

function calculateAvgResolutionTime(issues) {
    const resolvedIssues = issues.filter(i => i.resolvedAt && i.openedAt);
    
    if (resolvedIssues.length === 0) return 0;
    
    const totalTime = resolvedIssues.reduce((sum, issue) => {
        return sum + (issue.resolvedAt - issue.openedAt);
    }, 0);
    
    return Math.floor(totalTime / resolvedIssues.length / (1000 * 60 * 60 * 24));
}

// Show app statistics (can be called from console)
function showStats() {
    const stats = calculateStats();
    console.log('FixFirst Statistics:');
    console.log('====================');
    console.log(`Total Issues: ${stats.total}`);
    console.log(`On Deck: ${stats.onDeck}`);
    console.log(`In Progress: ${stats.inProgress}`);
    console.log(`Resolved: ${stats.resolved}`);
    console.log('');
    console.log(`High Priority: ${stats.high}`);
    console.log(`Medium Priority: ${stats.medium}`);
    console.log(`Low Priority: ${stats.low}`);
    console.log('');
    console.log(`Total Upvotes: ${stats.totalUpvotes}`);
    console.log(`Average Upvotes: ${stats.avgUpvotes}`);
    console.log(`Issues with Photos: ${stats.withPhotos}`);
    console.log(`Avg Resolution Time: ${stats.avgResolutionTime} days`);
    console.log('====================');
    return stats;
}

// ==================== DEVELOPMENT HELPERS ====================

// Quick login for testing (call from console)
function quickLoginCitizen() {
    const user = DB.users.find(u => u.role === 'citizen');
    AppState.setUser(user);
    showCitizenDashboard();
    console.log('Logged in as citizen');
}

function quickLoginAuthority() {
    const user = DB.users.find(u => u.role === 'authority');
    AppState.setUser(user);
    showAuthorityDashboard();
    console.log('Logged in as authority');
}

// Reset demo data
function resetDemoData() {
    if (confirm('Reset all demo data? This will reload the page.')) {
        location.reload();
    }
}

// Make helper functions available globally for console access
window.showStats = showStats;
window.exportIssuesCSV = exportIssuesCSV;
window.printIssueReport = printIssueReport;
window.quickLoginCitizen = quickLoginCitizen;
window.quickLoginAuthority = quickLoginAuthority;
window.resetDemoData = resetDemoData;

console.log('Helper functions available:');
console.log('- showStats() - Display app statistics');
console.log('- exportIssuesCSV() - Export data to CSV');
console.log('- printIssueReport(id) - Print issue report');
console.log('- quickLoginCitizen() - Quick login as citizen');
console.log('- quickLoginAuthority() - Quick login as authority');
console.log('- resetDemoData() - Reset and reload');